package com.example.friendify_backend_java.enums;

public enum ErrorCode {

    VALIDATION_ERROR,
    INVALID_REQUEST_FORMAT,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    DATABASE_ERROR,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    ACCOUNT_DISABLED,
    JWT_EXPIRED,
    INVALID_TOKEN,
    AUTHENTICATION_REQUIRED,
    CONFLICT_ERROR
}